@startsalt
skinparam monochrome true
skinparam defaultFontName Arial

{+
  <b>Интеллектуальный ассистент организации времени
  ==
  {
    ' Левая колонка: Чат с агентом
    {T
      + <b>Интерактивный диалог
      ++ <i>Пользователь:
      +++ Раскидай мне 3 лабы по сетям до конца месяца.
      ++ <i>Агент:
      +++ Я проанализировала загруженность и составила\nпредварительный план (3 спринта по 60 минут).\nПожалуйста, ознакомьтесь с черновиком в календаре.
      ++ ...
      ==
      "Введите запрос агенту...                       " | [ Отправить ]
    }
    |
    ' Правая колонка: Календарная сетка и управление
    {
      <b>Календарная сетка (Режим верификации черновика)
      {#
        <b>Время | <b>Среда (17.03) | <b>Четверг (18.03) | <b>Пятница (19.03)
        10:00 | [  Лекция БД  ] | .                 | .
        12:00 | .                 | [Лаба сети (1/3)] | .
        14:00 | [Лаба сети (2/3)] | .                 | [Лаба сети (3/3)]
        16:00 | .                 | [Английский яз.]  | .
      }
      ==
      { [Одобрить и сохранить в расписание] | [Отклонить и переделать] }
    }
  }
}
@endsalt